version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::630686402308:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-Y09LC2JGXZHW"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::630686402308:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1JA68SYRPBBA3"
cloudformation_execution_role = "arn:aws:iam::630686402308:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1GWI8WWT5R6UV"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-14cp7i08jrr18"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::630686402308:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-LLCE4D59L1NX"
cloudformation_execution_role = "arn:aws:iam::630686402308:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1U8G3KUJD7XR"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-tq65k0385arc"
image_repository = ""
region = "us-east-1"
